version: "3.8"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    expose:
      - 80
    networks:
      - internalnet
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - SERVER_HOST=frontend
      - SERVER_PORT=3000
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=Penisbutt123!
      - MYSQL_DATABASE=JobHunting
    ports:
      - "3306:3306"
    expose:
      - 3306 
    volumes:
      - ./server/mysql-init/:/docker-entrypoint-initdb.d
      - $HOME/database:/var/lib/mysql
    networks:
      - internalnet
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    expose:
      - 3000                                              
    environment:
      - REACT_APP_API_URL=http://backend:5050
    depends_on:
      - backend
    networks:
      - internalnet
  backend:
    build: ./server
    ports:
      - "5050:5000"
    # expose:
    #   - 5050 
    environment:
      - PORT=5050
      - CORS_ORIGIN=http://localhost:3000
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=Penisbutt123!
      - DB_NAME=JobHunting
    networks:
      - internalnet
    depends_on:
      - mysql
    restart: always
networks:
  internalnet:
    driver: bridge
